---
# name: hashicorp
# file: .pre-commit-config.yaml

repos:
  - repo: https://github.com/ansible-community/ansible-lint
    rev: v24.2.3
    hooks:
      - id: ansible-lint
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.25.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
